package stringfinder;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sunny
 */
public class WordDisplay extends javax.swing.JFrame {

  //JPopupMenu code basically copied from http://www.java2s.com/Code/Java/Swing-JFC/AsimpleexampleofJPopupMenu.htm
  public javax.swing.JPopupMenu popup;

  /**
   * Creates new form WordDisplay
   */
  public WordDisplay() {
    initComponents();
    DefaultTableModel model = (DefaultTableModel) JTWords.getModel();
    for (String[] sArray : WordStorage.getWordList()) {
      if (sArray.length != model.getColumnCount()) {
        System.out.println("ERROR: sArray size = " + sArray.length + " -- column count = " + model.getColumnCount() + " -- sizes different!");
        continue;
      }
      model.addRow(sArray);
    }
    popup = new javax.swing.JPopupMenu();
    java.awt.event.ActionListener menuListener = new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent event) {
        System.out.println("Popup menu item [" + event.getActionCommand() + "] was pressed.");
        System.out.println(event);
        System.out.println(event.getSource());
        if (event.getActionCommand().equals("Edit")) {
          System.out.println("Not supported yet.");
        } else if (event.getActionCommand().equals("Remove from List")) {
          System.out.println("PS: " + event.paramString());
//          WordStorage.removeWord(event.paramString());
        }
      }
    };
    javax.swing.JMenuItem item;
    popup.add(item = new javax.swing.JMenuItem("Edit"));
    item.setHorizontalTextPosition(javax.swing.JMenuItem.RIGHT);
    item.addActionListener(menuListener);
    popup.add(item = new javax.swing.JMenuItem("Remove from List"));
    item.setHorizontalTextPosition(javax.swing.JMenuItem.RIGHT);
    item.addActionListener(menuListener);
//    popup.addSeparator();
//    popup.add(item = new javax.swing.JMenuItem("Settings . . ."));
//    item.addActionListener(menuListener);

    popup.setLabel("Justification");
    popup.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));

    setLocationRelativeTo(null);
    setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    JTWords = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Words and Definitions");

    JTWords.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Word", "Definition"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    JTWords.setColumnSelectionAllowed(true);
    JTWords.getTableHeader().setReorderingAllowed(false);
    JTWords.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        JTWordsMouseReleased(evt);
      }
    });
    jScrollPane1.setViewportView(JTWords);
    JTWords.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        .addContainerGap())
      .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void JTWordsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTWordsMouseReleased
    // TODO add your handling code here:
    if (evt.isPopupTrigger()) {
        popup.show(this, evt.getX(), evt.getY());
        System.out.println("POPUP");
    }
  }//GEN-LAST:event_JTWordsMouseReleased

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTable JTWords;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
